// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// phylo_d_stream_cpp
Rcpp::List phylo_d_stream_cpp(const arma::vec& observed, const Rcpp::IntegerMatrix& edge, const arma::vec& edge_length, const int n_tip, const int nsim, const double prop_state1, const int chunk_size, const bool return_sim, const int n_threads);
RcppExport SEXP _fastphylosig_phylo_d_stream_cpp(SEXP observedSEXP, SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP n_tipSEXP, SEXP nsimSEXP, SEXP prop_state1SEXP, SEXP chunk_sizeSEXP, SEXP return_simSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type observed(observedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const int >::type n_tip(n_tipSEXP);
    Rcpp::traits::input_parameter< const int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< const double >::type prop_state1(prop_state1SEXP);
    Rcpp::traits::input_parameter< const int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_sim(return_simSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(phylo_d_stream_cpp(observed, edge, edge_length, n_tip, nsim, prop_state1, chunk_size, return_sim, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// delta_diagnostics_cpp
Rcpp::List delta_diagnostics_cpp(const arma::mat& alpha_chain, const arma::mat& beta_chain);
RcppExport SEXP _fastphylosig_delta_diagnostics_cpp(SEXP alpha_chainSEXP, SEXP beta_chainSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha_chain(alpha_chainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_chain(beta_chainSEXP);
    rcpp_result_gen = Rcpp::wrap(delta_diagnostics_cpp(alpha_chain, beta_chain));
    return rcpp_result_gen;
END_RCPP
}
// fast_k_chol_batch_cpp
arma::vec fast_k_chol_batch_cpp(const arma::mat& X, const arma::mat& cholC, const double traceC);
RcppExport SEXP _fastphylosig_fast_k_chol_batch_cpp(SEXP XSEXP, SEXP cholCSEXP, SEXP traceCSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cholC(cholCSEXP);
    Rcpp::traits::input_parameter< const double >::type traceC(traceCSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_k_chol_batch_cpp(X, cholC, traceC));
    return rcpp_result_gen;
END_RCPP
}
// fast_k_chol_permutation_cpp
Rcpp::List fast_k_chol_permutation_cpp(const arma::mat& X, const arma::mat& cholC, const double traceC, const Rcpp::IntegerMatrix& permutations, const int n_threads);
RcppExport SEXP _fastphylosig_fast_k_chol_permutation_cpp(SEXP XSEXP, SEXP cholCSEXP, SEXP traceCSEXP, SEXP permutationsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cholC(cholCSEXP);
    Rcpp::traits::input_parameter< const double >::type traceC(traceCSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type permutations(permutationsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_k_chol_permutation_cpp(X, cholC, traceC, permutations, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fast_k_chol_permutation_p_cpp
Rcpp::List fast_k_chol_permutation_p_cpp(const arma::mat& X, const arma::mat& cholC, const double traceC, const Rcpp::IntegerMatrix& permutations, const int n_threads);
RcppExport SEXP _fastphylosig_fast_k_chol_permutation_p_cpp(SEXP XSEXP, SEXP cholCSEXP, SEXP traceCSEXP, SEXP permutationsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cholC(cholCSEXP);
    Rcpp::traits::input_parameter< const double >::type traceC(traceCSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type permutations(permutationsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_k_chol_permutation_p_cpp(X, cholC, traceC, permutations, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// lambda_loglik_cpp
double lambda_loglik_cpp(const double lambda, const arma::mat& C, const arma::vec& y);
RcppExport SEXP _fastphylosig_lambda_loglik_cpp(SEXP lambdaSEXP, SEXP CSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_loglik_cpp(lambda, C, y));
    return rcpp_result_gen;
END_RCPP
}
// lambda_loglik_spectral_cpp
double lambda_loglik_spectral_cpp(const double lambda, const arma::vec& eigval, const arma::mat& eigvec, const arma::vec& inv_sqrt_diag, const double log_diag, const arma::vec& y);
RcppExport SEXP _fastphylosig_lambda_loglik_spectral_cpp(SEXP lambdaSEXP, SEXP eigvalSEXP, SEXP eigvecSEXP, SEXP inv_sqrt_diagSEXP, SEXP log_diagSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eigval(eigvalSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type eigvec(eigvecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type inv_sqrt_diag(inv_sqrt_diagSEXP);
    Rcpp::traits::input_parameter< const double >::type log_diag(log_diagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_loglik_spectral_cpp(lambda, eigval, eigvec, inv_sqrt_diag, log_diag, y));
    return rcpp_result_gen;
END_RCPP
}
// lambda_loglik_spectral_projected_cpp
double lambda_loglik_spectral_projected_cpp(const double lambda, const arma::vec& eigval, const arma::vec& wproj, const arma::vec& zproj, const double log_diag);
RcppExport SEXP _fastphylosig_lambda_loglik_spectral_projected_cpp(SEXP lambdaSEXP, SEXP eigvalSEXP, SEXP wprojSEXP, SEXP zprojSEXP, SEXP log_diagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eigval(eigvalSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wproj(wprojSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type zproj(zprojSEXP);
    Rcpp::traits::input_parameter< const double >::type log_diag(log_diagSEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_loglik_spectral_projected_cpp(lambda, eigval, wproj, zproj, log_diag));
    return rcpp_result_gen;
END_RCPP
}
// lambda_loglik_spectral_projected_batch_cpp
arma::mat lambda_loglik_spectral_projected_batch_cpp(const arma::vec& lambda, const arma::vec& eigval, const arma::vec& wproj, const arma::mat& zproj, const double log_diag, const int n_threads);
RcppExport SEXP _fastphylosig_lambda_loglik_spectral_projected_batch_cpp(SEXP lambdaSEXP, SEXP eigvalSEXP, SEXP wprojSEXP, SEXP zprojSEXP, SEXP log_diagSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eigval(eigvalSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wproj(wprojSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type zproj(zprojSEXP);
    Rcpp::traits::input_parameter< const double >::type log_diag(log_diagSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_loglik_spectral_projected_batch_cpp(lambda, eigval, wproj, zproj, log_diag, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// phylo_d_sums_cpp
arma::vec phylo_d_sums_cpp(const arma::mat& states, const Rcpp::IntegerMatrix& edge, const arma::vec& edge_length, const int n_tip, const int n_threads);
RcppExport SEXP _fastphylosig_phylo_d_sums_cpp(SEXP statesSEXP, SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP n_tipSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type states(statesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const int >::type n_tip(n_tipSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(phylo_d_sums_cpp(states, edge, edge_length, n_tip, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// brownian_threshold_cpp
Rcpp::IntegerMatrix brownian_threshold_cpp(const arma::mat& samples, const double prop_state1);
RcppExport SEXP _fastphylosig_brownian_threshold_cpp(SEXP samplesSEXP, SEXP prop_state1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const double >::type prop_state1(prop_state1SEXP);
    rcpp_result_gen = Rcpp::wrap(brownian_threshold_cpp(samples, prop_state1));
    return rcpp_result_gen;
END_RCPP
}
// brownian_tree_threshold_cpp
Rcpp::IntegerMatrix brownian_tree_threshold_cpp(const Rcpp::IntegerMatrix& edge, const arma::vec& edge_length, const int n_tip, const int nsim, const double prop_state1);
RcppExport SEXP _fastphylosig_brownian_tree_threshold_cpp(SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP n_tipSEXP, SEXP nsimSEXP, SEXP prop_state1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const int >::type n_tip(n_tipSEXP);
    Rcpp::traits::input_parameter< const int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< const double >::type prop_state1(prop_state1SEXP);
    rcpp_result_gen = Rcpp::wrap(brownian_tree_threshold_cpp(edge, edge_length, n_tip, nsim, prop_state1));
    return rcpp_result_gen;
END_RCPP
}
// fast_ace_discrete_deviance_cpp
double fast_ace_discrete_deviance_cpp(const Rcpp::IntegerMatrix& edge, const arma::vec& edge_length, const Rcpp::IntegerVector& tip_state, const Rcpp::IntegerMatrix& rate_index, const arma::vec& par, const bool reuse_buffers);
RcppExport SEXP _fastphylosig_fast_ace_discrete_deviance_cpp(SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP tip_stateSEXP, SEXP rate_indexSEXP, SEXP parSEXP, SEXP reuse_buffersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tip_state(tip_stateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type rate_index(rate_indexSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const bool >::type reuse_buffers(reuse_buffersSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_ace_discrete_deviance_cpp(edge, edge_length, tip_state, rate_index, par, reuse_buffers));
    return rcpp_result_gen;
END_RCPP
}
// fast_ace_discrete_liks_cpp
Rcpp::List fast_ace_discrete_liks_cpp(const Rcpp::IntegerMatrix& edge, const arma::vec& edge_length, const Rcpp::IntegerVector& tip_state, const Rcpp::IntegerMatrix& rate_index, const arma::vec& par, const bool marginal, const bool reuse_buffers);
RcppExport SEXP _fastphylosig_fast_ace_discrete_liks_cpp(SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP tip_stateSEXP, SEXP rate_indexSEXP, SEXP parSEXP, SEXP marginalSEXP, SEXP reuse_buffersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tip_state(tip_stateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type rate_index(rate_indexSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const bool >::type marginal(marginalSEXP);
    Rcpp::traits::input_parameter< const bool >::type reuse_buffers(reuse_buffersSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_ace_discrete_liks_cpp(edge, edge_length, tip_state, rate_index, par, marginal, reuse_buffers));
    return rcpp_result_gen;
END_RCPP
}
// delta_entropy_cpp
arma::vec delta_entropy_cpp(const arma::mat& probabilities, const int entropy_type);
RcppExport SEXP _fastphylosig_delta_entropy_cpp(SEXP probabilitiesSEXP, SEXP entropy_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type probabilities(probabilitiesSEXP);
    Rcpp::traits::input_parameter< const int >::type entropy_type(entropy_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(delta_entropy_cpp(probabilities, entropy_type));
    return rcpp_result_gen;
END_RCPP
}
// delta_mcmc_cpp
Rcpp::List delta_mcmc_cpp(const arma::mat& probabilities, const double lambda0, const double proposal_sd, const int sim, const int thin, const int burn, const int entropy_type, const bool return_chains);
RcppExport SEXP _fastphylosig_delta_mcmc_cpp(SEXP probabilitiesSEXP, SEXP lambda0SEXP, SEXP proposal_sdSEXP, SEXP simSEXP, SEXP thinSEXP, SEXP burnSEXP, SEXP entropy_typeSEXP, SEXP return_chainsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type probabilities(probabilitiesSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda0(lambda0SEXP);
    Rcpp::traits::input_parameter< const double >::type proposal_sd(proposal_sdSEXP);
    Rcpp::traits::input_parameter< const int >::type sim(simSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type entropy_type(entropy_typeSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_chains(return_chainsSEXP);
    rcpp_result_gen = Rcpp::wrap(delta_mcmc_cpp(probabilities, lambda0, proposal_sd, sim, thin, burn, entropy_type, return_chains));
    return rcpp_result_gen;
END_RCPP
}
// fast_k_tree_permutation_cpp
Rcpp::List fast_k_tree_permutation_cpp(const Rcpp::List& compiled_tree, const Rcpp::NumericMatrix& X, const int nsim, SEXP permutations, const int trait_chunk, const bool return_sim, const bool include_observed, const int n_threads, const int simulation_chunk);
RcppExport SEXP _fastphylosig_fast_k_tree_permutation_cpp(SEXP compiled_treeSEXP, SEXP XSEXP, SEXP nsimSEXP, SEXP permutationsSEXP, SEXP trait_chunkSEXP, SEXP return_simSEXP, SEXP include_observedSEXP, SEXP n_threadsSEXP, SEXP simulation_chunkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type compiled_tree(compiled_treeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< SEXP >::type permutations(permutationsSEXP);
    Rcpp::traits::input_parameter< const int >::type trait_chunk(trait_chunkSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_sim(return_simSEXP);
    Rcpp::traits::input_parameter< const bool >::type include_observed(include_observedSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type simulation_chunk(simulation_chunkSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_k_tree_permutation_cpp(compiled_tree, X, nsim, permutations, trait_chunk, return_sim, include_observed, n_threads, simulation_chunk));
    return rcpp_result_gen;
END_RCPP
}
// fast_k_tree_batch_cpp
Rcpp::List fast_k_tree_batch_cpp(const Rcpp::List& compiled_tree, const Rcpp::NumericMatrix& X, const int trait_chunk);
RcppExport SEXP _fastphylosig_fast_k_tree_batch_cpp(SEXP compiled_treeSEXP, SEXP XSEXP, SEXP trait_chunkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type compiled_tree(compiled_treeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type trait_chunk(trait_chunkSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_k_tree_batch_cpp(compiled_tree, X, trait_chunk));
    return rcpp_result_gen;
END_RCPP
}
// fast_lambda_tree_fixed_cpp
Rcpp::List fast_lambda_tree_fixed_cpp(const Rcpp::List& compiled_tree, const Rcpp::NumericMatrix& X, const Rcpp::NumericVector& lambda, const int trait_chunk, const int n_threads);
RcppExport SEXP _fastphylosig_fast_lambda_tree_fixed_cpp(SEXP compiled_treeSEXP, SEXP XSEXP, SEXP lambdaSEXP, SEXP trait_chunkSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type compiled_tree(compiled_treeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type trait_chunk(trait_chunkSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_lambda_tree_fixed_cpp(compiled_tree, X, lambda, trait_chunk, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fast_lambda_tree_optimize_cpp
Rcpp::List fast_lambda_tree_optimize_cpp(const Rcpp::List& compiled_tree, const Rcpp::NumericMatrix& X, SEXP max_lambda, const bool test, const bool profile, const int profile_points, const int trait_chunk, const int n_threads, const double tol);
RcppExport SEXP _fastphylosig_fast_lambda_tree_optimize_cpp(SEXP compiled_treeSEXP, SEXP XSEXP, SEXP max_lambdaSEXP, SEXP testSEXP, SEXP profileSEXP, SEXP profile_pointsSEXP, SEXP trait_chunkSEXP, SEXP n_threadsSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type compiled_tree(compiled_treeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max_lambda(max_lambdaSEXP);
    Rcpp::traits::input_parameter< const bool >::type test(testSEXP);
    Rcpp::traits::input_parameter< const bool >::type profile(profileSEXP);
    Rcpp::traits::input_parameter< const int >::type profile_points(profile_pointsSEXP);
    Rcpp::traits::input_parameter< const int >::type trait_chunk(trait_chunkSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_lambda_tree_optimize_cpp(compiled_tree, X, max_lambda, test, profile, profile_points, trait_chunk, n_threads, tol));
    return rcpp_result_gen;
END_RCPP
}
// group_na_masks_cpp
Rcpp::List group_na_masks_cpp(SEXP present);
RcppExport SEXP _fastphylosig_group_na_masks_cpp(SEXP presentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type present(presentSEXP);
    rcpp_result_gen = Rcpp::wrap(group_na_masks_cpp(present));
    return rcpp_result_gen;
END_RCPP
}
// compile_tree_cpp
Rcpp::List compile_tree_cpp(SEXP edge, SEXP edge_length, SEXP n_tip);
RcppExport SEXP _fastphylosig_compile_tree_cpp(SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP n_tipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_tip(n_tipSEXP);
    rcpp_result_gen = Rcpp::wrap(compile_tree_cpp(edge, edge_length, n_tip));
    return rcpp_result_gen;
END_RCPP
}
// tree_core_validate_cpp
Rcpp::List tree_core_validate_cpp(SEXP edge, SEXP edge_length, SEXP n_tip);
RcppExport SEXP _fastphylosig_tree_core_validate_cpp(SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP n_tipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_tip(n_tipSEXP);
    rcpp_result_gen = Rcpp::wrap(tree_core_validate_cpp(edge, edge_length, n_tip));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastphylosig_phylo_d_stream_cpp", (DL_FUNC) &_fastphylosig_phylo_d_stream_cpp, 9},
    {"_fastphylosig_delta_diagnostics_cpp", (DL_FUNC) &_fastphylosig_delta_diagnostics_cpp, 2},
    {"_fastphylosig_fast_k_chol_batch_cpp", (DL_FUNC) &_fastphylosig_fast_k_chol_batch_cpp, 3},
    {"_fastphylosig_fast_k_chol_permutation_cpp", (DL_FUNC) &_fastphylosig_fast_k_chol_permutation_cpp, 5},
    {"_fastphylosig_fast_k_chol_permutation_p_cpp", (DL_FUNC) &_fastphylosig_fast_k_chol_permutation_p_cpp, 5},
    {"_fastphylosig_lambda_loglik_cpp", (DL_FUNC) &_fastphylosig_lambda_loglik_cpp, 3},
    {"_fastphylosig_lambda_loglik_spectral_cpp", (DL_FUNC) &_fastphylosig_lambda_loglik_spectral_cpp, 6},
    {"_fastphylosig_lambda_loglik_spectral_projected_cpp", (DL_FUNC) &_fastphylosig_lambda_loglik_spectral_projected_cpp, 5},
    {"_fastphylosig_lambda_loglik_spectral_projected_batch_cpp", (DL_FUNC) &_fastphylosig_lambda_loglik_spectral_projected_batch_cpp, 6},
    {"_fastphylosig_phylo_d_sums_cpp", (DL_FUNC) &_fastphylosig_phylo_d_sums_cpp, 5},
    {"_fastphylosig_brownian_threshold_cpp", (DL_FUNC) &_fastphylosig_brownian_threshold_cpp, 2},
    {"_fastphylosig_brownian_tree_threshold_cpp", (DL_FUNC) &_fastphylosig_brownian_tree_threshold_cpp, 5},
    {"_fastphylosig_fast_ace_discrete_deviance_cpp", (DL_FUNC) &_fastphylosig_fast_ace_discrete_deviance_cpp, 6},
    {"_fastphylosig_fast_ace_discrete_liks_cpp", (DL_FUNC) &_fastphylosig_fast_ace_discrete_liks_cpp, 7},
    {"_fastphylosig_delta_entropy_cpp", (DL_FUNC) &_fastphylosig_delta_entropy_cpp, 2},
    {"_fastphylosig_delta_mcmc_cpp", (DL_FUNC) &_fastphylosig_delta_mcmc_cpp, 8},
    {"_fastphylosig_fast_k_tree_permutation_cpp", (DL_FUNC) &_fastphylosig_fast_k_tree_permutation_cpp, 9},
    {"_fastphylosig_fast_k_tree_batch_cpp", (DL_FUNC) &_fastphylosig_fast_k_tree_batch_cpp, 3},
    {"_fastphylosig_fast_lambda_tree_fixed_cpp", (DL_FUNC) &_fastphylosig_fast_lambda_tree_fixed_cpp, 5},
    {"_fastphylosig_fast_lambda_tree_optimize_cpp", (DL_FUNC) &_fastphylosig_fast_lambda_tree_optimize_cpp, 9},
    {"_fastphylosig_group_na_masks_cpp", (DL_FUNC) &_fastphylosig_group_na_masks_cpp, 1},
    {"_fastphylosig_compile_tree_cpp", (DL_FUNC) &_fastphylosig_compile_tree_cpp, 3},
    {"_fastphylosig_tree_core_validate_cpp", (DL_FUNC) &_fastphylosig_tree_core_validate_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastphylosig(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
