// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_k_chol_batch_cpp
arma::vec fast_k_chol_batch_cpp(const arma::mat& X, const arma::mat& cholC, const double traceC);
RcppExport SEXP _fastphylosig_fast_k_chol_batch_cpp(SEXP XSEXP, SEXP cholCSEXP, SEXP traceCSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cholC(cholCSEXP);
    Rcpp::traits::input_parameter< const double >::type traceC(traceCSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_k_chol_batch_cpp(X, cholC, traceC));
    return rcpp_result_gen;
END_RCPP
}
// fast_k_chol_permutation_cpp
Rcpp::List fast_k_chol_permutation_cpp(const arma::mat& X, const arma::mat& cholC, const double traceC, const Rcpp::IntegerMatrix& permutations, const int n_threads);
RcppExport SEXP _fastphylosig_fast_k_chol_permutation_cpp(SEXP XSEXP, SEXP cholCSEXP, SEXP traceCSEXP, SEXP permutationsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cholC(cholCSEXP);
    Rcpp::traits::input_parameter< const double >::type traceC(traceCSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type permutations(permutationsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_k_chol_permutation_cpp(X, cholC, traceC, permutations, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fast_k_chol_permutation_p_cpp
Rcpp::List fast_k_chol_permutation_p_cpp(const arma::mat& X, const arma::mat& cholC, const double traceC, const Rcpp::IntegerMatrix& permutations, const int n_threads);
RcppExport SEXP _fastphylosig_fast_k_chol_permutation_p_cpp(SEXP XSEXP, SEXP cholCSEXP, SEXP traceCSEXP, SEXP permutationsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cholC(cholCSEXP);
    Rcpp::traits::input_parameter< const double >::type traceC(traceCSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type permutations(permutationsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_k_chol_permutation_p_cpp(X, cholC, traceC, permutations, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// lambda_loglik_cpp
double lambda_loglik_cpp(const double lambda, const arma::mat& C, const arma::vec& y);
RcppExport SEXP _fastphylosig_lambda_loglik_cpp(SEXP lambdaSEXP, SEXP CSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_loglik_cpp(lambda, C, y));
    return rcpp_result_gen;
END_RCPP
}
// phylo_d_sums_cpp
arma::vec phylo_d_sums_cpp(const arma::mat& states, const Rcpp::IntegerMatrix& edge, const arma::vec& edge_length, const int n_tip, const int n_threads);
RcppExport SEXP _fastphylosig_phylo_d_sums_cpp(SEXP statesSEXP, SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP n_tipSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type states(statesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const int >::type n_tip(n_tipSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(phylo_d_sums_cpp(states, edge, edge_length, n_tip, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// brownian_threshold_cpp
Rcpp::IntegerMatrix brownian_threshold_cpp(const arma::mat& samples, const double prop_state1);
RcppExport SEXP _fastphylosig_brownian_threshold_cpp(SEXP samplesSEXP, SEXP prop_state1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const double >::type prop_state1(prop_state1SEXP);
    rcpp_result_gen = Rcpp::wrap(brownian_threshold_cpp(samples, prop_state1));
    return rcpp_result_gen;
END_RCPP
}
// brownian_tree_threshold_cpp
Rcpp::IntegerMatrix brownian_tree_threshold_cpp(const Rcpp::IntegerMatrix& edge, const arma::vec& edge_length, const int n_tip, const int nsim, const double prop_state1);
RcppExport SEXP _fastphylosig_brownian_tree_threshold_cpp(SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP n_tipSEXP, SEXP nsimSEXP, SEXP prop_state1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const int >::type n_tip(n_tipSEXP);
    Rcpp::traits::input_parameter< const int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< const double >::type prop_state1(prop_state1SEXP);
    rcpp_result_gen = Rcpp::wrap(brownian_tree_threshold_cpp(edge, edge_length, n_tip, nsim, prop_state1));
    return rcpp_result_gen;
END_RCPP
}
// fast_ace_discrete_deviance_cpp
double fast_ace_discrete_deviance_cpp(const Rcpp::IntegerMatrix& edge, const arma::vec& edge_length, const Rcpp::IntegerVector& tip_state, const Rcpp::IntegerMatrix& rate_index, const arma::vec& par);
RcppExport SEXP _fastphylosig_fast_ace_discrete_deviance_cpp(SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP tip_stateSEXP, SEXP rate_indexSEXP, SEXP parSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tip_state(tip_stateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type rate_index(rate_indexSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type par(parSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_ace_discrete_deviance_cpp(edge, edge_length, tip_state, rate_index, par));
    return rcpp_result_gen;
END_RCPP
}
// fast_ace_discrete_liks_cpp
Rcpp::List fast_ace_discrete_liks_cpp(const Rcpp::IntegerMatrix& edge, const arma::vec& edge_length, const Rcpp::IntegerVector& tip_state, const Rcpp::IntegerMatrix& rate_index, const arma::vec& par, const bool marginal);
RcppExport SEXP _fastphylosig_fast_ace_discrete_liks_cpp(SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP tip_stateSEXP, SEXP rate_indexSEXP, SEXP parSEXP, SEXP marginalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type tip_state(tip_stateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type rate_index(rate_indexSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type par(parSEXP);
    Rcpp::traits::input_parameter< const bool >::type marginal(marginalSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_ace_discrete_liks_cpp(edge, edge_length, tip_state, rate_index, par, marginal));
    return rcpp_result_gen;
END_RCPP
}
// delta_entropy_cpp
arma::vec delta_entropy_cpp(const arma::mat& probabilities, const int entropy_type);
RcppExport SEXP _fastphylosig_delta_entropy_cpp(SEXP probabilitiesSEXP, SEXP entropy_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type probabilities(probabilitiesSEXP);
    Rcpp::traits::input_parameter< const int >::type entropy_type(entropy_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(delta_entropy_cpp(probabilities, entropy_type));
    return rcpp_result_gen;
END_RCPP
}
// delta_mcmc_cpp
Rcpp::List delta_mcmc_cpp(const arma::mat& probabilities, const double lambda0, const double proposal_sd, const int sim, const int thin, const int burn, const int entropy_type);
RcppExport SEXP _fastphylosig_delta_mcmc_cpp(SEXP probabilitiesSEXP, SEXP lambda0SEXP, SEXP proposal_sdSEXP, SEXP simSEXP, SEXP thinSEXP, SEXP burnSEXP, SEXP entropy_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type probabilities(probabilitiesSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda0(lambda0SEXP);
    Rcpp::traits::input_parameter< const double >::type proposal_sd(proposal_sdSEXP);
    Rcpp::traits::input_parameter< const int >::type sim(simSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type entropy_type(entropy_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(delta_mcmc_cpp(probabilities, lambda0, proposal_sd, sim, thin, burn, entropy_type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastphylosig_fast_k_chol_batch_cpp", (DL_FUNC) &_fastphylosig_fast_k_chol_batch_cpp, 3},
    {"_fastphylosig_fast_k_chol_permutation_cpp", (DL_FUNC) &_fastphylosig_fast_k_chol_permutation_cpp, 5},
    {"_fastphylosig_fast_k_chol_permutation_p_cpp", (DL_FUNC) &_fastphylosig_fast_k_chol_permutation_p_cpp, 5},
    {"_fastphylosig_lambda_loglik_cpp", (DL_FUNC) &_fastphylosig_lambda_loglik_cpp, 3},
    {"_fastphylosig_phylo_d_sums_cpp", (DL_FUNC) &_fastphylosig_phylo_d_sums_cpp, 5},
    {"_fastphylosig_brownian_threshold_cpp", (DL_FUNC) &_fastphylosig_brownian_threshold_cpp, 2},
    {"_fastphylosig_brownian_tree_threshold_cpp", (DL_FUNC) &_fastphylosig_brownian_tree_threshold_cpp, 5},
    {"_fastphylosig_fast_ace_discrete_deviance_cpp", (DL_FUNC) &_fastphylosig_fast_ace_discrete_deviance_cpp, 5},
    {"_fastphylosig_fast_ace_discrete_liks_cpp", (DL_FUNC) &_fastphylosig_fast_ace_discrete_liks_cpp, 6},
    {"_fastphylosig_delta_entropy_cpp", (DL_FUNC) &_fastphylosig_delta_entropy_cpp, 2},
    {"_fastphylosig_delta_mcmc_cpp", (DL_FUNC) &_fastphylosig_delta_mcmc_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastphylosig(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
