# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_k_chol_batch_cpp <- function(X, cholC, traceC) {
    .Call(`_fastphylosig_fast_k_chol_batch_cpp`, X, cholC, traceC)
}

fast_k_chol_permutation_cpp <- function(X, cholC, traceC, permutations, n_threads = 1L) {
    .Call(`_fastphylosig_fast_k_chol_permutation_cpp`, X, cholC, traceC, permutations, n_threads)
}

fast_k_chol_permutation_p_cpp <- function(X, cholC, traceC, permutations, n_threads = 1L) {
    .Call(`_fastphylosig_fast_k_chol_permutation_p_cpp`, X, cholC, traceC, permutations, n_threads)
}

lambda_loglik_cpp <- function(lambda, C, y) {
    .Call(`_fastphylosig_lambda_loglik_cpp`, lambda, C, y)
}

phylo_d_sums_cpp <- function(states, edge, edge_length, n_tip, n_threads = 1L) {
    .Call(`_fastphylosig_phylo_d_sums_cpp`, states, edge, edge_length, n_tip, n_threads)
}

brownian_threshold_cpp <- function(samples, prop_state1) {
    .Call(`_fastphylosig_brownian_threshold_cpp`, samples, prop_state1)
}

brownian_tree_threshold_cpp <- function(edge, edge_length, n_tip, nsim, prop_state1) {
    .Call(`_fastphylosig_brownian_tree_threshold_cpp`, edge, edge_length, n_tip, nsim, prop_state1)
}

fast_ace_discrete_deviance_cpp <- function(edge, edge_length, tip_state, rate_index, par) {
    .Call(`_fastphylosig_fast_ace_discrete_deviance_cpp`, edge, edge_length, tip_state, rate_index, par)
}

fast_ace_discrete_liks_cpp <- function(edge, edge_length, tip_state, rate_index, par, marginal = FALSE) {
    .Call(`_fastphylosig_fast_ace_discrete_liks_cpp`, edge, edge_length, tip_state, rate_index, par, marginal)
}

delta_entropy_cpp <- function(probabilities, entropy_type) {
    .Call(`_fastphylosig_delta_entropy_cpp`, probabilities, entropy_type)
}

delta_mcmc_cpp <- function(probabilities, lambda0, proposal_sd, sim, thin, burn, entropy_type) {
    .Call(`_fastphylosig_delta_mcmc_cpp`, probabilities, lambda0, proposal_sd, sim, thin, burn, entropy_type)
}

