# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

phylo_d_stream_cpp <- function(observed, edge, edge_length, n_tip, nsim, prop_state1, chunk_size = 128L, return_sim = TRUE, n_threads = 1L) {
    .Call(`_fastphylosig_phylo_d_stream_cpp`, observed, edge, edge_length, n_tip, nsim, prop_state1, chunk_size, return_sim, n_threads)
}

delta_diagnostics_cpp <- function(alpha_chain, beta_chain) {
    .Call(`_fastphylosig_delta_diagnostics_cpp`, alpha_chain, beta_chain)
}

fast_k_chol_batch_cpp <- function(X, cholC, traceC) {
    .Call(`_fastphylosig_fast_k_chol_batch_cpp`, X, cholC, traceC)
}

fast_k_chol_permutation_cpp <- function(X, cholC, traceC, permutations, n_threads = 1L) {
    .Call(`_fastphylosig_fast_k_chol_permutation_cpp`, X, cholC, traceC, permutations, n_threads)
}

fast_k_chol_permutation_p_cpp <- function(X, cholC, traceC, permutations, n_threads = 1L) {
    .Call(`_fastphylosig_fast_k_chol_permutation_p_cpp`, X, cholC, traceC, permutations, n_threads)
}

lambda_loglik_cpp <- function(lambda, C, y) {
    .Call(`_fastphylosig_lambda_loglik_cpp`, lambda, C, y)
}

lambda_loglik_spectral_cpp <- function(lambda, eigval, eigvec, inv_sqrt_diag, log_diag, y) {
    .Call(`_fastphylosig_lambda_loglik_spectral_cpp`, lambda, eigval, eigvec, inv_sqrt_diag, log_diag, y)
}

lambda_loglik_spectral_projected_cpp <- function(lambda, eigval, wproj, zproj, log_diag) {
    .Call(`_fastphylosig_lambda_loglik_spectral_projected_cpp`, lambda, eigval, wproj, zproj, log_diag)
}

lambda_loglik_spectral_projected_batch_cpp <- function(lambda, eigval, wproj, zproj, log_diag, n_threads = 1L) {
    .Call(`_fastphylosig_lambda_loglik_spectral_projected_batch_cpp`, lambda, eigval, wproj, zproj, log_diag, n_threads)
}

phylo_d_sums_cpp <- function(states, edge, edge_length, n_tip, n_threads = 1L) {
    .Call(`_fastphylosig_phylo_d_sums_cpp`, states, edge, edge_length, n_tip, n_threads)
}

brownian_threshold_cpp <- function(samples, prop_state1) {
    .Call(`_fastphylosig_brownian_threshold_cpp`, samples, prop_state1)
}

brownian_tree_threshold_cpp <- function(edge, edge_length, n_tip, nsim, prop_state1) {
    .Call(`_fastphylosig_brownian_tree_threshold_cpp`, edge, edge_length, n_tip, nsim, prop_state1)
}

fast_ace_discrete_deviance_cpp <- function(edge, edge_length, tip_state, rate_index, par, reuse_buffers = FALSE) {
    .Call(`_fastphylosig_fast_ace_discrete_deviance_cpp`, edge, edge_length, tip_state, rate_index, par, reuse_buffers)
}

fast_ace_discrete_liks_cpp <- function(edge, edge_length, tip_state, rate_index, par, marginal = FALSE, reuse_buffers = FALSE) {
    .Call(`_fastphylosig_fast_ace_discrete_liks_cpp`, edge, edge_length, tip_state, rate_index, par, marginal, reuse_buffers)
}

delta_entropy_cpp <- function(probabilities, entropy_type) {
    .Call(`_fastphylosig_delta_entropy_cpp`, probabilities, entropy_type)
}

delta_mcmc_cpp <- function(probabilities, lambda0, proposal_sd, sim, thin, burn, entropy_type, return_chains = TRUE) {
    .Call(`_fastphylosig_delta_mcmc_cpp`, probabilities, lambda0, proposal_sd, sim, thin, burn, entropy_type, return_chains)
}

fast_k_tree_permutation_cpp <- function(compiled_tree, X, nsim = 1000L, permutations = NULL, trait_chunk = 64L, return_sim = FALSE, include_observed = TRUE, n_threads = 1L, simulation_chunk = 128L) {
    .Call(`_fastphylosig_fast_k_tree_permutation_cpp`, compiled_tree, X, nsim, permutations, trait_chunk, return_sim, include_observed, n_threads, simulation_chunk)
}

fast_k_tree_batch_cpp <- function(compiled_tree, X, trait_chunk = 64L) {
    .Call(`_fastphylosig_fast_k_tree_batch_cpp`, compiled_tree, X, trait_chunk)
}

fast_lambda_tree_fixed_cpp <- function(compiled_tree, X, lambda, trait_chunk = 64L, n_threads = 1L) {
    .Call(`_fastphylosig_fast_lambda_tree_fixed_cpp`, compiled_tree, X, lambda, trait_chunk, n_threads)
}

fast_lambda_tree_optimize_cpp <- function(compiled_tree, X, max_lambda = NULL, test = TRUE, profile = FALSE, profile_points = 101L, trait_chunk = 64L, n_threads = 1L, tol = 0.0001220703125) {
    .Call(`_fastphylosig_fast_lambda_tree_optimize_cpp`, compiled_tree, X, max_lambda, test, profile, profile_points, trait_chunk, n_threads, tol)
}

group_na_masks_cpp <- function(present) {
    .Call(`_fastphylosig_group_na_masks_cpp`, present)
}

compile_tree_cpp <- function(edge, edge_length, n_tip) {
    .Call(`_fastphylosig_compile_tree_cpp`, edge, edge_length, n_tip)
}

tree_core_validate_cpp <- function(edge, edge_length, n_tip) {
    .Call(`_fastphylosig_tree_core_validate_cpp`, edge, edge_length, n_tip)
}

